apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dnkkpnqkx-nodejs 
  janus-idp.io/tekton: dnkkpnqkx-nodejs
  backstage.io/kubernetes-id: dnkkpnqkx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dnkkpnqkx-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  