apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dnkkpnqkx-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8fdbc6eedb75bf35bcd93c88d7fdd731d4aa1315@sha256:585ce1d59c51a17e29dc7cee32befdc047cc9ba4f05eca0a6b2a912687c48f62
          name: container-image
